[env:photo_frame_gs_01]
platform = espressif32
framework = arduino
board = esp32dev
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.psram = enabled
board_build.psram_size = 4MB
board_build.psram_type = dio
board_build.psram_freq = 80M
board_build.arduino.loop_stack_size = 49152
board_upload.flash_size = 16MB
board_upload.maximum_ram_size = 524288
board_upload.maximum_size = 16777216
upload_port = COM4
upload_protocol = esptool
upload_speed = 921600
monitor_port = COM4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DCONFIG_SPIRAM_USE_MALLOC
	-DCONFIG_SPIRAM_CACHE_WORKAROUND
	-DCONFIG_SPIRAM_BANKSWITCH_ENABLE
	-DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
	-DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384
	-DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_EPD_DISPLAY_TYPE_ED047TC1
	-DCONFIG_EPD_BOARD_REVISION_LILYGO_T5_47
	-std=c++17
lib_deps = 
#	xinyuan-lilygo/LilyGoEPD47@^0.3.0
# bitbank2/JPEGDEC@^1.8.4
# xreef/SimpleFTPServer@^3.0.1
# arduino-libraries/ArduinoHttpClient@^0.6.1
test_ignore = *

[env:native]
platform = windows_x86
test_framework = unity
build_flags = -std=c++17
lib_deps = throwtheswitch/Unity@^2.6.0